### ISSUE TITLE
Figure 3

### ISSUE THREAD

**Issue by alpha-beta-soup** [manaakiwhenua/dggs-lu-tex#33]
The use of Red and Green colors in the figure, particularly the Venn/Euler diagram should be avoided. Instead some subset of color blind safe colors would be preferred, so as not to disadvantage certain cohorts of the readership. As an option, [Wang's Points of View: Color Blindness (2024)](https://www.nature.com/articles/nmeth.1618) provides RGB values for eight colors that are distinguishable by color blind readers.

**Comment by ChocopieKewpie** [comment]
We have put this figure through a colourblindness visualiser, and in our opinion all areas can be distinguished. We designed the graphs with the assumption that they would be printed in greyscale; therefore we have also incuded labels that make the colours superfluous.
